# ------------------------------------------------------------------------------
# ACME oneM2M IN-CSE Configuration Specification
# Software-Defined Vehicle (SDV) Automotive IoT HVAC Monitoring
# ------------------------------------------------------------------------------

[cse]
cseID = sdv-cse
cseName = sdv-cse
cseType = IN
adminID = CAdmin
dataDirectory = data
serviceProviderID = sdv.fhtw.at
supportedReleaseVersions = 2a,3,4
defaultSerialization = json
checkIntegrity = true

[cse.operation]
supportedOperations = CREATE,RETRIEVE,UPDATE,DELETE,NOTIFY

[http]
enable = true
address = 0.0.0.0
port = 8080
root = /
enableRemoteCSE = true

[database]
type = tinydb
path = data
cacheSize = 1000
resetOnStartup = false

[logging]
enable = true
level = info
file = ./data/acme.log
stackTraceOnError = false
enableScreen = true
